### ISSUE TITLE
webpack Error: Cannot resolve module 'jQuery'  

### ISSUE THREAD

**Issue by berndca** [jphalip/django-react-djangocon2015#1]
I'm getting the following errors when running webpack.

ERROR in ./photos/static/js/main.js
Module not found: Error: Cannot resolve module 'jQuery' in /home/bernd/Downloads/django-react-djangocon2015-master/photos/static/js
 @ ./photos/static/js/main.js 27:14-31

ERROR in ./photos/static/js/store.js
Module not found: Error: Cannot resolve module 'jQuery' in /home/bernd/Downloads/django-react-djangocon2015-master/photos/static/js
 @ ./photos/static/js/store.js 29:14-31

Bernd

BTW: Have you looked into more modern alternatives to jquery ajax?

**Comment by jphalip** [comment]
Hello. I'm not sure why you're getting this error. Have you run "npm install" and has it completed successfully? Is jquery present in the resulting "node_modules" folder?

I haven't looked into alternatives for jquery to run ajax calls. Would you have some recommendations?

Thanks!

**Comment by berndca** [comment]
Yes, I did run npm install before attempting the webpack build. I have included the first few lines (truncated) of the output below.

(jphalip)bernd@bernd-freya:~/Downloads/django-react-djangocon2015-master$ npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN peerDependencies The peer dependency babel-core@\* included from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
react-render@0.3.0 node_modules/react-render

uuid@2.0.1 node_modules/uuid

reflux@0.2.12 node_modules/reflux
├── eventemitter3@1.1.1
└── reflux-core@0.2.1

jquery@2.1.4 node_modules/jquery

lodash@3.10.1 node_modules/lodash

As far as ajax without jquery one could use a ployfill for the fetch API (https://github.com/github/fetch) or perhaps a much more powerful but lean library such as superagent (https://github.com/visionmedia/superagent). Both can be installed through npm and should work with webpack.

**Comment by berndca** [comment]
I noticed that the jQuery folder under node_modules is actually called "jquery" with lower case Q. I changed the import statements in question to this spelling in my local copy and it now works.

**Comment by jphalip** [comment]
@berndca Oh, that's interesting. I suppose it might have worked for me because my OSX partition isn't case sensitive. I'll push a fix, thanks! Thank you also for the ajax tips, I'll look into those.

**Comment by kurumkan** [comment]
@berndca  you better 

    npm install jQuery
instead 


    npm install jquery

And no need to rename folder names in node_modules
